### ISSUE TITLE
Turn off value silkscreen

### ISSUE THREAD

**Issue by osresearch** [Blinkinlabs/circuitpainter#2]
Is it possible to turn off the value silk screen, similar to `painter.no_designators()`?

**Comment by cibomahto** [comment]
It should be possible. It looks like the footprint function Value() allows access to that property, so it should work the same way as the Designator() function. Are you sure that you're seeing a value on the silkscreen layer, though, and not the F.Fab layer?

This is how the no_designators() option works:

https://github.com/Blinkinlabs/circuitpainter/blob/2bd61c05d2e95a6f9190e44400243a81141e0926/src/circuitpainter/circuitpainter.py#L438

**Comment by osresearch** [comment]
That worked:
```
                fp = painter.footprint(0,0, ... )
                fp.Value().SetVisible(False)
```

**Comment by cibomahto** [comment]
Great. It looks like all of the default KiCad footprints have value on the F.Fab layer, but there's nothing stopping you from making a custom footprint with a different assignment. So I agree that editing the object directly is probably the way to go here.
